"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ems-flasher-gui.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'iconfile':'emsgui.icns',
    'plist': {
        'CFBundleShortVersionString':'0.1.0',
        'LSMinimumSystemVersion':'10.9',
        'NSHumanReadableCopyright':'Copyright © 2016 Daniele Biggiogero. Software released under MIT License'
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
